'use client';

import { useGameState } from '@/app/lib/store';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { 
  ChevronLeft, Gift, Zap, Crown, Award, 
  ShieldCheck, TrendingUp, Users, Coins, 
  Target, HeartPulse, GraduationCap, Package,
  Hammer, Sparkles, Gem, Flame, Skull, Box, Info
} from 'lucide-react';
import Link from 'next/link';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';

interface GiftTypeItem {
  id: string;
  label: string;
  desc: string;
  impact: string;
  icon: any;
  color: string;
  rarity: 'Common' | 'Rare' | 'Epic' | 'Legendary';
}

export default function BonusesKnowledgePage() {
  const { language } = useGameState();

  const gifts: GiftTypeItem[] = [
    {
      id: 'architect',
      label: language === 'ru' ? "Архитектор Метавселенной" : "Metaverse Architect",
      desc: language === 'ru' ? "Сверхзвуковой логистический модуль. Сокращает время текущего строительства на 2, 6 или 12 часов." : "Supersonic logistics module. Reduces current construction time by 2, 6, or 12 hours.",
      impact: "Time Skip",
      icon: Hammer,
      color: "text-orange-400",
      rarity: 'Epic'
    },
    {
      id: 'grant',
      label: language === 'ru' ? "Венчурный Грант" : "Venture Grant",
      desc: language === 'ru' ? "Прямое финансирование от межгалактических инвесторов. Пополняет бюджет клуба на сумму от 1M до 5M €." : "Direct funding from intergalactic investors. Refills club budget by 1M to 5M €.",
      impact: "+Credits",
      icon: TrendingUp,
      color: "text-green-400",
      rarity: 'Rare'
    },
    {
      id: 'shard',
      label: language === 'ru' ? "Осколок Еремеевита" : "Jeremejevite Shard",
      desc: language === 'ru' ? "Концентрированная энергия в кристаллической форме. Мгновенно добавляет от 50 до 250 алмазов." : "Concentrated energy in crystalline form. Instantly adds 50 to 250 diamonds.",
      impact: "+Crystals",
      icon: Gem,
      color: "text-blue-400",
      rarity: 'Rare'
    },
    {
      id: 'teambuilding',
      label: language === 'ru' ? "Тимбилдинг на Мальдивах" : "Maldives Teambuilding",
      desc: language === 'ru' ? "Экстренный отпуск для команды. Мгновенно восстанавливает форму и дает бонусный опыт всем игрокам." : "Emergency vacation for the team. Instantly restores form and grants bonus XP to all players.",
      impact: "Form & XP",
      icon: HeartPulse,
      color: "text-pink-400",
      rarity: 'Epic'
    },
    {
      id: 'secret',
      label: language === 'ru' ? "Секретный Сундук" : "Secret Chest",
      desc: language === 'ru' ? "Зашифрованный контейнер. Содержит случайный высокоуровневый актив или редкий расходник." : "Encrypted container. Contains a random high-level asset or a rare consumable.",
      impact: "Random Loot",
      icon: Box,
      color: "text-yellow-500",
      rarity: 'Legendary'
    },
    {
      id: 'curse',
      label: language === 'ru' ? "Проклятие Гения" : "Genius Curse",
      desc: language === 'ru' ? "Экспериментальный нейромодулятор. Дает огромный бонус к одному навыку ценой временного падения выносливости." : "Experimental neuromodulator. Grants a massive bonus to one skill at the cost of temporary stamina decay.",
      impact: "Stat Swap",
      icon: Flame,
      color: "text-red-500",
      rarity: 'Common'
    }
  ];

  const t = {
    ru: {
      title: "РЕЕСТР ПОДАРКОВ",
      subtitle: "Дипломатические грузы S-Tier",
      impact: "Эффект",
      rarityLabel: "Редкость",
      desc: "Эти грузы могут быть сгенерированы игроками с лицензией S-Tier и отправлены друзьям как жест доброй воли или тактическая поддержка."
    },
    en: {
      title: "GIFT REGISTRY",
      subtitle: "S-Tier Diplomatic Cargo",
      impact: "Impact",
      rarityLabel: "Rarity",
      desc: "These packages can be generated by S-Tier managers and sent to friends as a gesture of goodwill or tactical support."
    }
  }[language === 'ru' ? 'ru' : 'en'];

  return (
    <div className="max-w-md mx-auto px-4 pt-8 pb-32">
      <header className="mb-8 flex items-center gap-4">
        <Link href="/system">
          <Button variant="ghost" size="icon" className="rounded-full bg-secondary/50 border border-white/5">
            <ChevronLeft className="w-6 h-6" />
          </Button>
        </Link>
        <div>
          <h1 className="text-2xl font-headline font-bold uppercase tracking-tighter text-white">{t.title}</h1>
          <p className="text-muted-foreground text-[10px] uppercase tracking-widest font-black opacity-50">{t.subtitle}</p>
        </div>
      </header>

      <Card className="bg-primary/5 border-primary/20 mb-8">
        <CardContent className="p-4 flex gap-4">
          <Info className="w-5 h-5 text-primary shrink-0" />
          <p className="text-[10px] text-muted-foreground leading-relaxed italic">
            "{t.desc}"
          </p>
        </CardContent>
      </Card>

      <div className="space-y-3">
        {gifts.map((gift) => (
          <Card key={gift.id} className="glass-card border-white/5 bg-secondary/10 group hover:border-primary/30 transition-all active:scale-[0.98]">
            <CardContent className="p-4">
              <div className="flex items-start gap-4">
                <div className={cn("p-2.5 rounded-xl bg-secondary/50 border border-white/5 shrink-0 shadow-inner group-hover:scale-110 transition-transform", gift.color)}>
                  <gift.icon className="w-6 h-6" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex justify-between items-start mb-1">
                    <h3 className="text-sm font-bold uppercase text-white truncate mr-2">{gift.label}</h3>
                    <Badge variant="outline" className={cn(
                      "text-[7px] font-black uppercase h-4 px-1.5",
                      gift.rarity === 'Legendary' ? "border-yellow-500/50 text-yellow-500" :
                      gift.rarity === 'Epic' ? "border-purple-500/50 text-purple-400" :
                      gift.rarity === 'Rare' ? "border-blue-500/50 text-blue-400" :
                      "border-white/20 text-muted-foreground"
                    )}>
                      {gift.rarity}
                    </Badge>
                  </div>
                  <p className="text-[10px] text-muted-foreground leading-relaxed italic mb-3">
                    "{gift.desc}"
                  </p>
                  <div className="flex items-center gap-2">
                    <span className="text-[8px] font-black text-primary uppercase tracking-widest">{t.impact}:</span>
                    <Badge className="bg-primary/20 text-primary text-[8px] font-bold uppercase border-primary/30">
                      {gift.impact}
                    </Badge>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
